# Generated by Django 2.2 on 2019-04-29 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sides', models.TextField()),
                ('name', models.TextField()),
                ('cost', models.IntegerField(blank=True, null=True)),
                ('health', models.IntegerField(blank=True, null=True)),
                ('has_die', models.BooleanField()),
                ('url', models.TextField()),
                ('img_src', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
