# Generated by Django 2.2 on 2019-04-29 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='sides',
            field=models.TextField(blank=True, null=True),
        ),
    ]
