# Generated by Django 2.2 on 2019-05-10 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190429_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='type_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
