# Generated by Django 2.2 on 2019-05-14 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_card_type_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
