# Generated by Django 2.2 on 2019-05-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190514_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='dmg',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
