# Generated by Django 2.2 on 2019-05-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_card_dmg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='dmg',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
